# Very annoyingly, there is no way for a WSGI app to leverage Apache's
# knowledge of MIME types. Therefore we must configure a bunch of common
# ones.
#
# This has the syntax of an Apache config file, but it's not read by
# Apache, only by archiveblock.wsgi.
#
# This does not include types defined in ifarchive.conf.

AddType application/java-archive jar
AddType application/json json
AddType application/octet-stream ico
AddType application/pdf pdf PDF
AddType application/postscript ps PS
AddType application/rtf rtf RTF
AddType application/wasm wasm
AddType application/x-apple-diskimage dmg
AddType application/x-bzip2 bz2
AddType application/x-compress z Z
AddType application/x-gzip .gz .tgz
AddType application/xml xml iFiction
AddType application/zip zip ZIP
AddType audio/mp4 m4a
AddType audio/mpeg mp3
AddType audio/ogg ogg
AddType audio/x-wav wav
AddType font/ttf ttf TTF
AddType font/woff woff
AddType image/gif gif GIF
AddType image/jpeg jpg JPG jpeg JPEG
AddType image/png png PNG
AddType image/svg+xml svg
AddType image/tiff tif tiff
AddType text/csv csv
AddType text/html;charset=utf-8 html HTML htm HTM shtml SHTML
AddType text/markdown md
AddType text/plain txt TXT
AddType text/x-c++src cpp CPP
AddType text/x-chdr h H
AddType text/x-csrc c C
AddType video/mp4 mp4
